name: setup

description: Set up a Python environment.

inputs:
  version:
    description: Which Python version to install
    required: false
    default: "3.11"

runs:
  using: composite
  steps:
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.version }}

    - name: Install project requirements
      shell: bash
      run: pip install -r requirements/requirements.txt
